package cmd

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var sddCmd = &cobra.Command{
	Use:   "sdd",
	Short: "Spec-Driven Development commands",
	Long:  `SDD (Spec-Driven Development) workflow commands for autonomous feature development.`,
	Run: func(cmd *cobra.Command, args []string) {
		_ = cmd.Help()
	},
}

var sddProposeCmd = &cobra.Command{
	Use:   "propose",
	Short: "Create SDD change proposal",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")
		title, _ := cmd.Flags().GetString("title")
		body, _ := cmd.Flags().GetString("body")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		proposalDir := filepath.Join(".atl", "proposals")
		if err := os.MkdirAll(proposalDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(proposalDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Proposal: %s

**Issue**: #%d

%s

---
*Generated by ayrton sdd propose*
`, title, issueNum, body)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddSpecCmd = &cobra.Command{
	Use:   "spec",
	Short: "Write SDD delta specifications",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		specDir := filepath.Join(".atl", "specs")
		if err := os.MkdirAll(specDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(specDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Spec: Issue #%d

**Issue**: #%d

## Requirements
- [ ] Requirement 1
- [ ] Requirement 2

## Scenarios
- [ ] Scenario 1
- [ ] Scenario 2

## Acceptance Criteria
- [ ] Criterion 1

---
*Generated by ayrton sdd spec*
`, issueNum, issueNum)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddDesignCmd = &cobra.Command{
	Use:   "design",
	Short: "Create technical design document",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		designDir := filepath.Join(".atl", "designs")
		if err := os.MkdirAll(designDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(designDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Design: Issue #%d

**Issue**: #%d

## Architecture Overview
- TBD

## Components
- Component 1: TBD
- Component 2: TBD

## Data Flow
- TBD

## API Contracts
- TBD

## Security Considerations
- TBD

## Testing Strategy
- Unit tests
- Integration tests

---
*Generated by ayrton sdd design*
`, issueNum, issueNum)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddTasksCmd = &cobra.Command{
	Use:   "tasks",
	Short: "Break change into implementation tasks",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		tasksDir := filepath.Join(".atl", "tasks")
		if err := os.MkdirAll(tasksDir, 0755); err != nil {
			return err
		}

		path := filepath.Join(tasksDir, fmt.Sprintf("%d.md", issueNum))
		content := fmt.Sprintf(`# SDD Tasks: Issue #%d

**Issue**: #%d

## Implementation Tasks
- [ ] Task 1: Setup/preparation
- [ ] Task 2: Core implementation
- [ ] Task 3: Tests
- [ ] Task 4: Documentation
- [ ] Task 5: Code review

## Dependencies
- None

## Estimated Effort
- TBD

---
*Generated by ayrton sdd tasks*
`, issueNum, issueNum)

		return os.WriteFile(path, []byte(content), 0644)
	},
}

var sddApplyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Implement SDD tasks (requires AI agent)",
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		fmt.Fprintf(os.Stderr, "⚠️  SDD apply phase requires an AI coding agent\n")
		fmt.Fprintf(os.Stderr, "   This CLI provides the structure; implementation needs an AI agent\n")
		fmt.Fprintf(os.Stderr, "   See .atl/tasks/%d.md for the task list\n", issueNum)
		fmt.Fprintf(os.Stderr, "\n")
		fmt.Fprintf(os.Stderr, "To implement with an AI agent:\n")
		fmt.Fprintf(os.Stderr, "  1. Read the spec: .atl/specs/%d.md\n", issueNum)
		fmt.Fprintf(os.Stderr, "  2. Read the design: .atl/designs/%d.md\n", issueNum)
		fmt.Fprintf(os.Stderr, "  3. Follow tasks: .atl/tasks/%d.md\n", issueNum)
		fmt.Fprintf(os.Stderr, "  4. Implement each task\n")
		fmt.Fprintf(os.Stderr, "  5. Run: ayrton sdd verify --issue %d\n", issueNum)

		return nil
	},
}

// verifyResult holds the outcome of a verification step
type verifyResult struct {
	Name   string
	Passed bool
	Output string
	Dur    time.Duration
}

var sddVerifyCmd = &cobra.Command{
	Use:   "verify",
	Short: "Run tests and verify implementation",
	RunE: func(cmd *cobra.Command, args []string) error {
		results := runVerification()

		fmt.Println()
		fmt.Println("╔══════════════════════════════════════════╗")
		fmt.Println("║        SDD Verification Report           ║")
		fmt.Println("╚══════════════════════════════════════════╝")
		fmt.Println()

		allPassed := true
		for _, r := range results {
			status := "✅ PASS"
			if !r.Passed {
				status = "❌ FAIL"
				allPassed = false
			}
			fmt.Printf("%s  %s  (%s)\n", status, r.Name, r.Dur.Round(time.Millisecond))
			if !r.Passed || r.Output != "" {
				fmt.Println(strings.TrimSpace(r.Output))
				fmt.Println()
			}
		}

		fmt.Println(strings.Repeat("─", 46))
		passed := 0
		for _, r := range results {
			if r.Passed {
				passed++
			}
		}
		fmt.Printf("Results: %d/%d passed\n", passed, len(results))

		if !allPassed {
			fmt.Println("\n❌ Verification FAILED — fix issues above and re-run")
			return fmt.Errorf("verification failed")
		}
		fmt.Println("\n✅ Verification PASSED — all checks green")
		return nil
	},
}

func runVerification() []verifyResult {
	var results []verifyResult

	results = append(results, runStep("go vet", "go", "vet", "./..."))
	results = append(results, runStep("go test -race", "go", "test", "-race", "-count=1", "./..."))
	results = append(results, runStep("go build", "go", "build", "./..."))

	// golangci-lint is optional (not always installed locally)
	if _, err := exec.LookPath("golangci-lint"); err == nil {
		results = append(results, runStep("golangci-lint", "golangci-lint", "run", "--timeout=5m"))
	}

	return results
}

func runStep(name string, prog string, args ...string) verifyResult {
	start := time.Now()
	var stdout, stderr bytes.Buffer

	cmd := exec.Command(prog, args...)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr
	err := cmd.Run()
	dur := time.Since(start)

	out := strings.TrimSpace(stdout.String() + "\n" + stderr.String())
	passed := err == nil
	return verifyResult{Name: name, Passed: passed, Output: out, Dur: dur}
}

var sddArchiveCmd = &cobra.Command{
	Use:   "archive",
	Short: "Archive completed SDD change",
	Long:  `Clean up .atl artifacts for an issue and close it on GitHub.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		issueNum, _ := cmd.Flags().GetInt("issue")

		if issueNum == 0 {
			return fmt.Errorf("--issue is required")
		}

		atlDir := filepath.Join(".atl")

		type artifact struct {
			Dir  string
			Path string
		}
		var removed []artifact

		// Collect all .atl files for this issue
		for _, sub := range []string{"proposals", "specs", "designs", "tasks"} {
			path := filepath.Join(atlDir, sub, fmt.Sprintf("%d.md", issueNum))
			if _, err := os.Stat(path); err == nil {
				removed = append(removed, artifact{Dir: sub, Path: path})
			}
		}

		// Remove them
		for _, a := range removed {
			if err := os.Remove(a.Path); err != nil {
				fmt.Fprintf(os.Stderr, "⚠️  failed to remove %s: %v\n", a.Path, err)
			}
		}

		fmt.Println()
		fmt.Println("╔══════════════════════════════════════════╗")
		fmt.Println("║        SDD Archive Report               ║")
		fmt.Println("╚══════════════════════════════════════════╝")
		fmt.Println()

		if len(removed) > 0 {
			fmt.Printf("Cleaned up %d artifact(s) for issue #%d:\n", len(removed), issueNum)
			for _, a := range removed {
				fmt.Printf("  🗑️  .atl/%-12s %d.md\n", a.Dir+"/", issueNum)
			}
		} else {
			fmt.Printf("No .atl artifacts found for issue #%d\n", issueNum)
		}
		fmt.Println()

		// Close issue on GitHub
		if _, err := exec.LookPath("gh"); err == nil {
			fmt.Printf("Closing issue #%d on GitHub...\n", issueNum)
			cmd := exec.Command("gh", "issue", "close", fmt.Sprintf("%d", issueNum), "--comment", "Archived via `ayrton sdd archive`")
			var stderr bytes.Buffer
			cmd.Stderr = &stderr
			if err := cmd.Run(); err != nil {
				fmt.Fprintf(os.Stderr, "⚠️  gh issue close failed: %s\n", strings.TrimSpace(stderr.String()))
			} else {
				fmt.Printf("✅ Issue #%d closed on GitHub\n", issueNum)
			}
		} else {
			fmt.Fprintf(os.Stderr, "⚠️  gh CLI not found — skipping GitHub issue close\n")
			fmt.Fprintf(os.Stderr, "   Install: https://cli.github.com/\n")
		}

		fmt.Println()
		fmt.Println(strings.Repeat("─", 46))
		fmt.Println("✅ Archive complete")
		return nil
	},
}

func init() {
	sddProposeCmd.Flags().Int("issue", 0, "GitHub issue number")
	sddProposeCmd.Flags().String("title", "", "Issue title")
	sddProposeCmd.Flags().String("body", "", "Issue body")
	_ = sddProposeCmd.MarkFlagRequired("issue")

	sddSpecCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddSpecCmd.MarkFlagRequired("issue")

	sddDesignCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddDesignCmd.MarkFlagRequired("issue")

	sddTasksCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddTasksCmd.MarkFlagRequired("issue")

	sddApplyCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddApplyCmd.MarkFlagRequired("issue")

	sddVerifyCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddVerifyCmd.MarkFlagRequired("issue")

	sddArchiveCmd.Flags().Int("issue", 0, "GitHub issue number")
	_ = sddArchiveCmd.MarkFlagRequired("issue")

	sddCmd.AddCommand(
		sddProposeCmd,
		sddSpecCmd,
		sddDesignCmd,
		sddTasksCmd,
		sddApplyCmd,
		sddVerifyCmd,
		sddArchiveCmd,
	)

	rootCmd.AddCommand(sddCmd)
}